version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_HOST=0.0.0.0
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  flask:
    build: https://raw.githubusercontent.com/KhvatikG/gpp-flask-test-serv/main/Dockerfile
    container_name: gpp-flask-test-serv
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python gpp-flask-test-server.py
